spring:
  datasource:
    url: jdbc:mysql://118.31.7.229:3307/user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xym123
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: auth
  redis:
    database: 8
    host: 118.31.7.229
    port: 6379
    password: xym123

server:
  port: 8770
  servlet:
    context-path: /auth
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8770
    ip-address: 192.168.1.101
  client:
    serviceUrl:
      defaultZone: http://118.31.7.229:8761/eureka
aaron:
  machine-id: 1
  data-center-id: 110
  version: 1
